In [1]:
import data_wrangling
data_wrangling.get_version()

INFO:data_wrangling.core:data_wrangling library version: 0.2.0

data_wrangling library version: 0.2.0

'0.2.0'

In [2]:
from data_wrangling import DataInspector

inspector = DataInspector()
inspector.load_data('test_dataset.csv')

✅ File 'test_dataset.csv' loaded successfully!
--- Data Summary  ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             20               0
1                age     int64             20               0
2             salary   float64             20               4
3         department    object             20               3
4         is_manager    object             20               0
5   experience_years   float64             20               2
6  performance_score   float64             20               1
7              count     int64             20               0

In [9]:
# View a detailed summary with statistical metrics
summary_df = inspector.get_summary(detailed=True)

--- Data Summary (Detailed) ---

,Column Name,Data Type,Total Records,Missing Values,Min,Max,Mean,Std Dev,Unique Values,Most Frequent
0,id,int64,16,0,1.0,20.0,10.5625,6.334759,NaN,NaN
1,age,int64,16,0,22.0,50.0,33.5625,7.831294,NaN,NaN
2,salary,float64,16,0,50000.0,120000.0,73125.0000,19462.356829,NaN,NaN
3,department,object,16,2,NaN,NaN,NaN,NaN,3.0,Engineering
4,is_manager,object,16,0,NaN,NaN,NaN,NaN,2.0,No
5,experience_years,float64,16,0,1.0,20.0,7.9375,5.230918,NaN,NaN
6,performance_score,float64,16,0,60.0,98.0,83.7500,9.801360,NaN,NaN
7,count,int64,16,0,1.0,1.0,1.0000,0.000000,NaN,NaN

### Test: Finding Missing Data

In [ ]:
# Show rows with missing data
missing_rows = inspector.get_missing_data(axis='rows')

In [ ]:
# Show columns with missing data
missing_cols = inspector.get_missing_data(axis='columns')

### Test: Deleting Rows and Columns

In [ ]:
# Delete row indices 10 and 15 (duplicates in our test dataset)
inspector.delete_rows([10, 15], summary=True)

In [ ]:
# Delete the 'count' column that gets automatically added
inspector.delete_columns(['count'], summary=True)

### Test: Data Extraction

In [ ]:
# Extract specific numerical columns and rows (e.g. indices 0-5), keeping the 'id' column.
num_df = inspector.extract_data(column_type='numerical', index_column='id', row_ranges=[(0, 5)])

In [ ]:
# Extract specific numerical columns and rows (e.g. indices 0-5), keeping the 'id' column.
num_df = inspector.extract_data(column_type='categorical', index_column='id', row_ranges=[(1,3),(5, 8)])

### Test: Data Exporting

In [ ]:
# Export the selected data with a timestamped JSON summary
inspector.export_data(file_name='my_test_export', export_summary=True)

### Test: Reset DataFrame

In [13]:
# Reset the dataframe back to its original state before any deletions
inspector.reset_df()

✅ DataFrame reset to original state.
--- Data Summary  ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             20               0
1                age     int64             20               0
2             salary   float64             20               4
3         department    object             20               3
4         is_manager    object             20               0
5   experience_years   float64             20               2
6  performance_score   float64             20               1
7              count     int64             20               0

### Test: Data Modification (Impute, Duplicates, Outliers, Normalize)

In [4]:
# 1. Handle missing values (e.g. median imputation)
inspector.modify_missing_values(strategy='median')

🛠️ Missing values imputed using 'median' strategy for: ['salary', 'department', 'experience_years', 'performance_score']

In [6]:
# 2. Remove duplicates
inspector.modify_duplicates()

✨ Removed 2 duplicate rows. New row count: 18

In [8]:
# 3. Flag and delete outliers (e.g. from the 'age' column)
inspector.modify_outliers(columns=['age'], find_and_delete=True)

🚨 age: Found 2 outliers.
🗑️ Deleted 2 outlier rows total.

In [15]:
# 4. Normalize a numerical column and encode a categorical column
inspector.modify_normalize_data(columns=['salary'], method='standard', replace=False)
inspector.modify_normalize_data(columns=['department'], method='onehot', replace=False)

# Check out the updated dataframe!
summary_df= inspector.get_summary()

✨ Successfully applied 'standard' to ['salary'].
✨ Successfully applied 'onehot' to ['department'].
--- Data Summary  ---

               Column Name Data Type  Total Records  Missing Values
0                       id     int64             20               0
1                      age     int64             20               0
2                   salary   float64             20               4
3               department    object             20               3
4               is_manager    object             20               0
5         experience_years   float64             20               2
6        performance_score   float64             20               1
7                    count     int64             20               0
8          salary_standard   float64             20               0
9   department_Engineering   float64             20               0
10           department_HR   float64             20               0
11      department_Missing   float64             20               0
12        department_Sales   float64             20               0

In [16]:
inspector.df

,id,age,salary,department,is_manager,experience_years,performance_score,count,salary_standard,department_Engineering,department_HR,department_Missing,department_Sales
0,1,25,50000.0,Engineering,No,2.0,75.0,1,-1.206878,1.0,0.0,0.0,0.0
1,2,30,60000.0,Sales,No,5.0,80.0,1,-0.663239,0.0,0.0,0.0,1.0
2,3,45,120000.0,Engineering,Yes,15.0,95.0,1,2.598594,1.0,0.0,0.0,0.0
3,4,22,NaN,HR,No,1.0,60.0,1,-0.173964,0.0,1.0,0.0,0.0
4,5,150,70000.0,Engineering,No,8.0,85.0,1,-0.119601,1.0,0.0,0.0,0.0
5,6,35,80000.0,NaN,Yes,NaN,90.0,1,0.424038,0.0,0.0,1.0,0.0
6,7,40,NaN,Sales,Yes,12.0,92.0,1,-0.173964,0.0,0.0,0.0,1.0
7,8,28,55000.0,HR,No,4.0,78.0,1,-0.935059,0.0,1.0,0.0,0.0
8,9,-5,45000.0,Sales,No,2.0,70.0,1,-1.478698,0.0,0.0,0.0,1.0
9,10,50,NaN,Engineering,Yes,20.0,98.0,1,-0.173964,1.0,0.0,0.0,0.0
10,10,50,NaN,Engineering,Yes,20.0,98.0,1,-0.173964,1.0,0.0,0.0,0.0
11,12,33,75000.0,HR,Yes,7.0,NaN,1,0.152219,0.0,1.0,0.0,0.0
12,13,29,62000.0,Sales,No,6.0,82.0,1,-0.554512,0.0,0.0,0.0,1.0
13,14,27,58000.0,Engineering,No,NaN,79.0,1,-0.771967,1.0,0.0,0.0,0.0
14,15,38,90000.0,NaN,Yes,10.0,88.0,1,0.967677,0.0,0.0,1.0,0.0
15,15,38,90000.0,NaN,Yes,10.0,88.0,1,0.967677,0.0,0.0,1.0,0.0
16,17,31,68000.0,Engineering,No,5.0,83.0,1,-0.228328,1.0,0.0,0.0,0.0
17,18,42,105000.0,Sales,Yes,14.0,94.0,1,1.783135,0.0,0.0,0.0,1.0
18,19,26,52000.0,HR,No,2.0,72.0,1,-1.098150,0.0,1.0,0.0,0.0
19,20,36,88000.0,Engineering,Yes,9.0,89.0,1,0.858949,1.0,0.0,0.0,0.0