In [1]:
import data_wrangling
data_wrangling.get_version()

INFO:data_wrangling.core:data_wrangling library version: 0.1.1

data_wrangling library version: 0.1.1

'0.1.1'

In [3]:
from data_wrangling import DataInspector

inspector = DataInspector()
inspector.load_data('test_dataset.csv')

✅ File 'test_dataset.csv' loaded successfully!
--- Data Summary ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             20               0
1                age     int64             20               0
2             salary   float64             20               4
3         department    object             20               3
4         is_manager    object             20               0
5   experience_years   float64             20               2
6  performance_score   float64             20               1
7              count     int64             20               0

### Test: Finding Missing Data

In [4]:
# Show rows with missing data
missing_rows = inspector.get_missing_data(axis='rows')

🔍 Found 9 rows with missing values.

,id,age,salary,department,is_manager,experience_years,performance_score,count
3,4,22,NaN,HR,No,1.0,60.0,1
5,6,35,80000.0,NaN,Yes,NaN,90.0,1
6,7,40,NaN,Sales,Yes,12.0,92.0,1
9,10,50,NaN,Engineering,Yes,20.0,98.0,1
10,10,50,NaN,Engineering,Yes,20.0,98.0,1

In [5]:
# Show columns with missing data
missing_cols = inspector.get_missing_data(axis='columns')

🔍 Found 4 columns with missing values.

     salary   department  experience_years  performance_score
0   50000.0  Engineering               2.0               75.0
1   60000.0        Sales               5.0               80.0
2  120000.0  Engineering              15.0               95.0
3       NaN           HR               1.0               60.0
4   70000.0  Engineering               8.0               85.0

### Test: Deleting Rows and Columns

In [7]:
# Delete row indices 10 and 15 (duplicates in our test dataset)
inspector.delete_rows([10, 15], summary=True)

🗑️ Deleted 2 rows. New count: 18
--- Data Summary ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             18               0
1                age     int64             18               0
2             salary   float64             18               3
3         department    object             18               2
4         is_manager    object             18               0
5   experience_years   float64             18               2
6  performance_score   float64             18               1
7              count     int64             18               0

In [8]:
# Delete the 'count' column that gets automatically added
inspector.delete_columns(['count'], summary=True)

🗑️ Deleted 1 columns. Remaining count: 7
--- Data Summary ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             18               0
1                age     int64             18               0
2             salary   float64             18               3
3         department    object             18               2
4         is_manager    object             18               0
5   experience_years   float64             18               2
6  performance_score   float64             18               1

In [10]:
# View the newly updated summary (since we removed it during deletion)
summary_df= inspector.get_summary()

--- Data Summary ---

         Column Name Data Type  Total Records  Missing Values
0                 id     int64             18               0
1                age     int64             18               0
2             salary   float64             18               3
3         department    object             18               2
4         is_manager    object             18               0
5   experience_years   float64             18               2
6  performance_score   float64             18               1